import type { Achievement } from '@/models'

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-lesson',
    title: 'First Lesson',
    description: 'Complete your first lesson.',
    category: 'milestone',
    icon: '01',
    order: 1,
  },
  {
    id: 'first-quiz',
    title: 'First Quiz',
    description: 'Complete your first quiz.',
    category: 'milestone',
    icon: '02',
    order: 2,
  },
  {
    id: 'perfect-score',
    title: 'Perfect Score',
    description: 'Score 100% on a quiz.',
    category: 'mastery',
    icon: '★',
    order: 3,
  },
  {
    id: 'streak-7',
    title: '7 Day Streak',
    description: 'Study 7 days in a row.',
    category: 'streak',
    icon: '07',
    order: 4,
  },
  {
    id: 'streak-30',
    title: '30 Day Streak',
    description: 'Study 30 days in a row.',
    category: 'streak',
    icon: '30',
    order: 5,
  },
  {
    id: 'streak-100',
    title: '100 Day Streak',
    description: 'Study 100 days in a row.',
    category: 'streak',
    icon: '100',
    order: 6,
  },
  {
    id: 'lessons-100',
    title: '100 Lessons',
    description: 'Complete 100 lessons.',
    category: 'milestone',
    icon: '100',
    order: 7,
  },
  {
    id: 'javascript-explorer',
    title: 'JavaScript Explorer',
    description: 'Complete the JavaScript Deep Dive subject.',
    category: 'exploration',
    icon: 'JS',
    order: 8,
  },
  {
    id: 'typescript-explorer',
    title: 'TypeScript Explorer',
    description: 'Complete the TypeScript Deep Dive subject.',
    category: 'exploration',
    icon: 'TS',
    order: 9,
  },
  {
    id: 'react-expert',
    title: 'React Expert',
    description: 'Complete the React Internals subject.',
    category: 'exploration',
    icon: 'RE',
    order: 10,
  },
  {
    id: 'react-native-explorer',
    title: 'React Native Explorer',
    description: 'Complete RN Fundamentals and RN Advanced.',
    category: 'exploration',
    icon: 'RN',
    order: 11,
  },
  {
    id: 'jsi-explorer',
    title: 'JSI Explorer',
    description: 'Complete the JSI subject.',
    category: 'exploration',
    icon: 'JI',
    order: 12,
  },
  {
    id: 'performance-detective',
    title: 'Performance Detective',
    description: 'Complete 5 performance-tagged challenges.',
    category: 'craft',
    icon: 'PF',
    order: 13,
  },
  {
    id: 'bug-hunter',
    title: 'Bug Hunter',
    description: 'Log 10 real-world problems.',
    category: 'craft',
    icon: 'BG',
    order: 14,
  },
  {
    id: 'architecture-thinker',
    title: 'Architecture Thinker',
    description: 'Log 10 engineering decisions.',
    category: 'craft',
    icon: 'AR',
    order: 15,
  },
  {
    id: 'android-explorer',
    title: 'Native Android Explorer',
    description: 'Complete the Android Fundamentals subject.',
    category: 'exploration',
    icon: 'AN',
    order: 16,
  },
  {
    id: 'ios-explorer',
    title: 'Native iOS Explorer',
    description: 'Complete the iOS Fundamentals subject.',
    category: 'exploration',
    icon: 'IO',
    order: 17,
  },
]

export const ACHIEVEMENTS_BY_ID: Record<string, Achievement> = Object.fromEntries(
  ACHIEVEMENTS.map((achievement) => [achievement.id, achievement]),
)
