import type { Subject } from '@/models'

/**
 * The 34 top-level roadmap categories from the product spec, in recommended learning order.
 * `recommendedPrerequisites` drives the "locked / recommended / available" state in the roadmap
 * UI — it is advisory, not enforced, so an experienced engineer can jump ahead freely.
 */
export const SUBJECTS: Subject[] = [
  {
    id: 'javascript-deep-dive',
    order: 1,
    title: 'JavaScript Deep Dive',
    shortTitle: 'JavaScript',
    description: 'Execution model, event loop, closures, prototypes, async patterns.',
    track: 'javascript',
    recommendedPrerequisites: [],
    icon: 'JS',
    estimatedHours: 18,
  },
  {
    id: 'typescript-deep-dive',
    order: 2,
    title: 'TypeScript Deep Dive',
    shortTitle: 'TypeScript',
    description: 'Structural typing, generics, narrowing, and type-level design for real apps.',
    track: 'javascript',
    recommendedPrerequisites: ['javascript-deep-dive'],
    icon: 'TS',
    estimatedHours: 14,
  },
  {
    id: 'react-internals',
    order: 3,
    title: 'React Internals',
    shortTitle: 'React Internals',
    description: 'Fiber, reconciliation, scheduling, hooks internals, concurrent rendering.',
    track: 'javascript',
    recommendedPrerequisites: ['javascript-deep-dive'],
    icon: 'RE',
    estimatedHours: 16,
  },
  {
    id: 'react-native-fundamentals',
    order: 4,
    title: 'React Native Fundamentals',
    shortTitle: 'RN Fundamentals',
    description: 'Core components, styling, navigation basics, the RN mental model.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-internals'],
    icon: 'RN',
    estimatedHours: 12,
  },
  {
    id: 'react-native-advanced',
    order: 5,
    title: 'React Native Advanced',
    shortTitle: 'RN Advanced',
    description: 'Native modules, gesture systems, animation drivers, platform-specific code.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-fundamentals'],
    icon: 'RN',
    estimatedHours: 16,
  },
  {
    id: 'react-native-architecture',
    order: 6,
    title: 'React Native Architecture',
    shortTitle: 'RN Architecture',
    description: 'The classic Bridge: serialization, batching, and why it existed.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-fundamentals'],
    icon: 'AR',
    estimatedHours: 8,
  },
  {
    id: 'react-native-new-architecture',
    order: 7,
    title: 'React Native New Architecture',
    shortTitle: 'New Architecture',
    description: 'How JSI, Fabric, TurboModules, and Codegen fit together as one system.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-architecture'],
    icon: 'NA',
    estimatedHours: 10,
  },
  {
    id: 'hermes',
    order: 8,
    title: 'Hermes',
    shortTitle: 'Hermes',
    description: "React Native's JS engine: bytecode precompilation, GC, startup performance.",
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-new-architecture'],
    icon: 'HE',
    estimatedHours: 8,
  },
  {
    id: 'jsi',
    order: 9,
    title: 'JSI',
    shortTitle: 'JSI',
    description: 'Direct, synchronous JS-to-native calls via HostObjects and HostFunctions.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-new-architecture'],
    icon: 'JI',
    estimatedHours: 10,
  },
  {
    id: 'fabric',
    order: 10,
    title: 'Fabric',
    shortTitle: 'Fabric',
    description: 'The new rendering system: shadow tree, C++ core, synchronous layout.',
    track: 'react-native-core',
    recommendedPrerequisites: ['jsi'],
    icon: 'FB',
    estimatedHours: 10,
  },
  {
    id: 'turbomodules',
    order: 11,
    title: 'TurboModules',
    shortTitle: 'TurboModules',
    description: 'Lazily-loaded, JSI-backed native modules and their type-safe specs.',
    track: 'react-native-core',
    recommendedPrerequisites: ['jsi'],
    icon: 'TM',
    estimatedHours: 8,
  },
  {
    id: 'codegen',
    order: 12,
    title: 'Codegen',
    shortTitle: 'Codegen',
    description: 'Generating native interface code from TypeScript/Flow specs.',
    track: 'react-native-core',
    recommendedPrerequisites: ['turbomodules'],
    icon: 'CG',
    estimatedHours: 6,
  },
  {
    id: 'react-native-performance',
    order: 13,
    title: 'React Native Performance',
    shortTitle: 'RN Performance',
    description: 'Frame budgets, list virtualization, bridge/JSI traffic, memory profiling.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-advanced'],
    icon: 'PF',
    estimatedHours: 14,
  },
  {
    id: 'react-native-debugging',
    order: 14,
    title: 'React Native Debugging',
    shortTitle: 'RN Debugging',
    description: 'Flipper/DevTools, native debuggers, crash triage, systematic root-causing.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-advanced'],
    icon: 'DB',
    estimatedHours: 8,
  },
  {
    id: 'networking',
    order: 15,
    title: 'Networking',
    shortTitle: 'Networking',
    description: 'HTTP fundamentals, caching, retries, request cancellation on mobile.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-fundamentals'],
    icon: 'NW',
    estimatedHours: 10,
  },
  {
    id: 'offline-first',
    order: 16,
    title: 'Offline First Applications',
    shortTitle: 'Offline First',
    description: 'Local persistence, sync strategies, conflict resolution, optimistic UI.',
    track: 'react-native-core',
    recommendedPrerequisites: ['networking'],
    icon: 'OF',
    estimatedHours: 12,
  },
  {
    id: 'state-management',
    order: 17,
    title: 'State Management',
    shortTitle: 'State Mgmt',
    description: 'Local vs. global vs. server state, and choosing the right tool.',
    track: 'react-native-core',
    recommendedPrerequisites: ['react-native-fundamentals'],
    icon: 'SM',
    estimatedHours: 10,
  },
  {
    id: 'android-fundamentals',
    order: 18,
    title: 'Native Android Fundamentals',
    shortTitle: 'Android',
    description: 'Activities, lifecycle, Gradle, the pieces RN sits on top of.',
    track: 'native',
    recommendedPrerequisites: ['react-native-advanced'],
    icon: 'AN',
    estimatedHours: 14,
  },
  {
    id: 'kotlin-for-rn',
    order: 19,
    title: 'Kotlin for React Native Developers',
    shortTitle: 'Kotlin',
    description: 'Enough Kotlin to read and write Android native modules confidently.',
    track: 'native',
    recommendedPrerequisites: ['android-fundamentals'],
    icon: 'KT',
    estimatedHours: 10,
  },
  {
    id: 'ios-fundamentals',
    order: 20,
    title: 'Native iOS Fundamentals',
    shortTitle: 'iOS',
    description: 'App lifecycle, view controllers, Xcode, the pieces RN sits on top of.',
    track: 'native',
    recommendedPrerequisites: ['react-native-advanced'],
    icon: 'IO',
    estimatedHours: 14,
  },
  {
    id: 'swift-for-rn',
    order: 21,
    title: 'Swift for React Native Developers',
    shortTitle: 'Swift',
    description: 'Enough Swift to read and write iOS native modules confidently.',
    track: 'native',
    recommendedPrerequisites: ['ios-fundamentals'],
    icon: 'SW',
    estimatedHours: 10,
  },
  {
    id: 'push-notifications',
    order: 22,
    title: 'Push Notifications',
    shortTitle: 'Push',
    description: 'APNs, FCM, token lifecycle, delivery guarantees and their limits.',
    track: 'native',
    recommendedPrerequisites: ['networking'],
    icon: 'PN',
    estimatedHours: 6,
  },
  {
    id: 'deep-linking',
    order: 23,
    title: 'Deep Linking',
    shortTitle: 'Deep Linking',
    description: 'Universal links, App Links, and reliable in-app navigation from them.',
    track: 'native',
    recommendedPrerequisites: ['react-native-advanced'],
    icon: 'DL',
    estimatedHours: 5,
  },
  {
    id: 'mobile-security',
    order: 24,
    title: 'Mobile Security',
    shortTitle: 'Security',
    description: 'Secure storage, cert pinning, jailbreak/root detection, OWASP MASVS.',
    track: 'native',
    recommendedPrerequisites: ['networking'],
    icon: 'SC',
    estimatedHours: 10,
  },
  {
    id: 'testing',
    order: 25,
    title: 'Testing',
    shortTitle: 'Testing',
    description: 'Unit, component, integration, and E2E testing strategy for mobile apps.',
    track: 'craft',
    recommendedPrerequisites: ['react-native-fundamentals'],
    icon: 'TE',
    estimatedHours: 12,
  },
  {
    id: 'ci-cd',
    order: 26,
    title: 'CI/CD',
    shortTitle: 'CI/CD',
    description: 'Build pipelines, signing, Fastlane, staged rollouts for mobile releases.',
    track: 'craft',
    recommendedPrerequisites: ['testing'],
    icon: 'CI',
    estimatedHours: 8,
  },
  {
    id: 'app-stores',
    order: 27,
    title: 'App Store and Google Play',
    shortTitle: 'App Stores',
    description: 'Review guidelines, release management, staged rollouts, versioning.',
    track: 'craft',
    recommendedPrerequisites: ['ci-cd'],
    icon: 'AS',
    estimatedHours: 5,
  },
  {
    id: 'backend-fundamentals',
    order: 28,
    title: 'Backend Fundamentals',
    shortTitle: 'Backend',
    description: 'Client-server model, statelessness, auth, the shape of a backend service.',
    track: 'backend',
    recommendedPrerequisites: ['networking'],
    icon: 'BE',
    estimatedHours: 10,
  },
  {
    id: 'nodejs',
    order: 29,
    title: 'Node.js',
    shortTitle: 'Node.js',
    description: "The event loop from the server's side, streams, and building real services.",
    track: 'backend',
    recommendedPrerequisites: ['backend-fundamentals'],
    icon: 'ND',
    estimatedHours: 12,
  },
  {
    id: 'databases',
    order: 30,
    title: 'Databases',
    shortTitle: 'Databases',
    description: 'Relational vs. document models, indexing, and picking the right store.',
    track: 'backend',
    recommendedPrerequisites: ['backend-fundamentals'],
    icon: 'DA',
    estimatedHours: 12,
  },
  {
    id: 'api-design',
    order: 31,
    title: 'API Design',
    shortTitle: 'API Design',
    description: 'REST conventions, versioning, pagination, and designing for mobile clients.',
    track: 'backend',
    recommendedPrerequisites: ['backend-fundamentals'],
    icon: 'AD',
    estimatedHours: 8,
  },
  {
    id: 'websockets',
    order: 32,
    title: 'WebSockets',
    shortTitle: 'WebSockets',
    description: 'Real-time transport, reconnection strategy, and mobile battery tradeoffs.',
    track: 'backend',
    recommendedPrerequisites: ['api-design'],
    icon: 'WS',
    estimatedHours: 6,
  },
  {
    id: 'system-design',
    order: 33,
    title: 'System Design',
    shortTitle: 'System Design',
    description: 'Scalability, consistency, caching, and reasoning about distributed systems.',
    track: 'backend',
    recommendedPrerequisites: ['databases', 'api-design'],
    icon: 'SD',
    estimatedHours: 16,
  },
  {
    id: 'mobile-system-design',
    order: 34,
    title: 'Mobile System Design',
    shortTitle: 'Mobile Sys Design',
    description: 'End-to-end mobile architecture interviews: sync, offline, scale, tradeoffs.',
    track: 'react-native-core',
    recommendedPrerequisites: ['system-design', 'offline-first'],
    icon: 'MS',
    estimatedHours: 14,
  },
]

export const SUBJECTS_BY_ID: Record<string, Subject> = Object.fromEntries(
  SUBJECTS.map((subject) => [subject.id, subject]),
)

export const SUBJECT_TRACKS: { id: Subject['track']; label: string }[] = [
  { id: 'javascript', label: 'JavaScript & React Foundations' },
  { id: 'react-native-core', label: 'React Native Core & Internals' },
  { id: 'native', label: 'Native Platforms' },
  { id: 'craft', label: 'Engineering Craft' },
  { id: 'backend', label: 'Backend & Systems' },
]
